name: Manually Deploy to Heroku

on:
  workflow_dispatch:
    branches:
      - "heroku"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.API}}
          heroku_app_name: ${{secrets.NAME}}
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_CONFIG_URL: ${{secrets.CONFIG_URL}}
